language: java
jdk: openjdk11

install: true
script: rm -rf $HOME/.m2 && ./mvnw clean test -B

cache:
  directories:
    - $HOME/.m2

git:
  depth: 1

# blocklist
branches:
  except:
    - l10n_master
