name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Install dependencies
        run: sudo apt-get install genisoimage ghostscript nsis

      - name: Install Java
        uses: actions/setup-java@v1
        with:
          java-version: 15
          java-package: jdk

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Cache packaging dependencies
        id: cache-bootstrap
        uses: actions/cache@v2
        with:
          path: |
            ./dist/dmg
            ./dist/jdks
            ./dist/launch4j
          key: ${{ runner.os }}-m2-${{ hashFiles('bootstrap.sh') }}

      - name: Install packaging dependencies
        if: steps.cache-bootstrap.outputs.cache-hit != 'true'
        run: ./bootstrap.sh

      - name: Build packages
        run: make release

      - name: Archive packages
        uses: actions/upload-artifact@v2
        with:
          name: packages
          path: |
            tmp/VASSAL-*-linux.tar.bz2
            tmp/VASSAL-*-macos.dmg
            tmp/VASSAL-*-other.zip
            tmp/VASSAL-*-windows-32.exe
            tmp/VASSAL-*-windows-64.exe
            tmp/VASSAL-*.sha256
